<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Google.Apis.Sheets.v4" Version="1.67.0.3365" />
      <PackageReference Include="Telegram.Bot" Version="19.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BotCommon\BotCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="BotMessages.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>BotMessages.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="BotMessages.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>BotMessages.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <None Update="Dockerfile">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>