<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release;StyleCheck</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'StyleCheck'">
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
<!--        HACK: Эту ошибку игнорируем из-за slf4j-api.-->
        <WarningsNotAsErrors>NU1701</WarningsNotAsErrors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AnalysisMode>AllEnabledByDefault</AnalysisMode>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' != 'StyleCheck'">
        <EnableNETAnalyzers>false</EnableNETAnalyzers>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="slf4j-api" Version="1.7.5.4" />
      <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
      <PackageReference Include="System.Reflection.Emit" Version="4.7.0" />
      <PackageReference Include="Telegram.Bot" Version="19.0.0" />
      <PackageReference Include="IKVM" Version="8.7.5" />
      <PackageReference Include="IKVM.Maven.Sdk" Version="1.6.8" PrivateAssets="all" />
      <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
         <PrivateAssets>all</PrivateAssets>
         <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BotCommon\BotCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
        <MavenReference Include="edu.stanford.nlp:stanford-corenlp" Version="4.5.6"/>
        <MavenReference Include="edu.stanford.nlp:stanford-corenlp" Version="4.5.6" Classifier="models" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="BotMessages.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>BotMessages.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="BotMessages.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>BotMessages.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <Content Include="stanford.nlp.models/edu.stanford.nlp.corenlp_english_models.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <None Update="NLog.config">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>